[package]
name = "nuget-tui"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = { version = "0.30", features = ["serde"] }
crossterm = {version = "0.29.0", features = ["event-stream"]}
futures = "0.3"
tui-input = { version = "*", features = ["crossterm"], default-features = false }
walkdir = "2"
roxmltree = "0.21.1"
tracing-appender = "0.2"

# Async
tokio = { version = "1", features = ["full"] }

# HTTP + Serialization
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

# Error handling
anyhow = "1"
thiserror = "2"

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Config & paths
config = "0.15"
directories = "6"
